### ISSUE TITLE
PSR-2 and PSR-4

### ISSUE THREAD

**Issue by vinkla** [jenssegers/laravel-date#109]
What about adding PSR-2 and PSR-4 standards to this package? What do you think @jenssegers? I could help out with that.

**Comment by jenssegers** [comment]
I couldn't add PSR-4 because of compatibility support with Laravel 4. I just did a big push and made it PSR-4 for the new release.

**Comment by vinkla** [comment]
Very nice! What about PSR-4:ing the tests as well and adding PSR-2?
