### ISSUE TITLE
Drop PHP 5.3 support

### ISSUE THREAD

**Issue by vinkla** [jenssegers/laravel-date#114]
Since you have integrated this with Laravel PHP `5.3` can't be supported. Laravel `>=4.0` requires at least PHP `~5.4.7`. Either we create separate packages for core and Laravel or remove PHP `5.3` support in this package. 

This will help us create tests for the Laravel integration as well. We currently can't do that since the tests will fail due to the missing `illuminate/support` package.

What do you think about this @jenssegers?

**Comment by jenssegers** [comment]
I'm all up for dropping PHP 5.3 support, but I don't know if many people are still using this version. But since this started out as a Laravel package, I think we can drop it.

**Comment by vinkla** [comment]
Great! Then I could push a service provider test to #113 as well. What you think?
