### ISSUE TITLE
How to make Laravel use Date instead of Carbon when pulling dates from database

### ISSUE THREAD

**Issue by d3mueller** [jenssegers/laravel-date#121]
Hi,

Larval uses Carbon to convert timestamps from the database (created_at, updated_at and custom ones) into a Carbon object. Is there a way to make Laravel use laravel-date instead?

thank you for your help

**Comment by d3mueller** [comment]
Sorry, I didn't see the "closed" tab. This question has been asked before

**Comment by AlexKevler** [comment]
You can use Mutator possibility of Laravel Eloquent to use laravel-date.
In your models, set functions like this :
```php
// Assuming using Jenssegers\Date\Date in your class

public function getCreatedAtAttribute($attr)
{
	if(!is_null($attr)) {
		return Date::parse($attr);
	}

	return null;
}

public function getUpdatedAtAttribute($attr)
{
	if(!is_null($attr)) {
		return Date::parse($attr);
	}

	return null;
}

// If your model is softDelete capable
public function getDeletedAtAttribute($attr)
{
	if(!is_null($attr)) {
		return Date::parse($attr);
	}

	return null;
}
```

**Comment by vinkla** [comment]
@d3mueller Since you've found the answer maybe you could close this?

**Comment by Deleugpn** [comment]
Where?

**Comment by danhunsaker** [comment]
See #44.
