### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by aktiWeb** [jenssegers/laravel-date#125]
Hi,

after composer installation and adding the ServiceProvider i get the following error message:

*ErrorException in Date.php line 6:
Declaration of Jenssegers\Date\Date::setTranslator() should be compatible with Carbon\Carbon::setTranslator(Symfony\Component\Translation\TranslatorInterface $translator)*

What i made wrong?

(Using Laravel 5)

**Comment by fabioi** [comment]
+1

**Comment by jenssegers** [comment]
See https://github.com/jenssegers/laravel-date/issues/112

**Comment by aktiWeb** [comment]
"composer update" has downgraded nesbot/carbon from 1.18 to 1.17 but all works fine now.
