### ISSUE TITLE
Cannot make it work with Laravel 5

### ISSUE THREAD

**Issue by zeusent** [jenssegers/laravel-date#127]
So i've just installed your module using the instructions of the README file here (`composer require jenssegers/date`) on github and it somehow broke my Laravel 5 installation.

I did saw an older issue that had the same problem but I have NO idea what to do to fix this.

The error I get is this:

>**ErrorException in Date.php line 343:**
>Declaration of Jenssegers\Date\Date::setTranslator() should be compatible with Carbon\Carbon::setTranslator(Symfony\Component\Translation\TranslatorInterface $translator)

Any help would be appreciated,
Mickey

**Comment by jenssegers** [comment]
Make sure you are using the ~3.0 version.

**Comment by zeusent** [comment]
Well that doesn't really help. Doing the "simple" `composer require jessegers/date` thing added `"jenssegers/date": "~2.0"` to my composer.json

Now if I try to change that to `"jenssegers/date": "~3.0"` I get the following error in the terminal when doing `composer update`:
>
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - The requested package jenssegers/date could not be found in any version, there may be a typo in the package name.
Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.
Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

So... Any more clues?

**Comment by jenssegers** [comment]
v3 was still marked as pre-release. I just tagged the official release, packagist just needs some time to detect it I guess.

**Comment by zeusent** [comment]
Ha! Now that was a coincidence :D It worked :+1:
