### ISSUE TITLE
[feature request] different formats for toFormattedDateString

### ISSUE THREAD

**Issue by AndreasHeiberg** [jenssegers/laravel-date#136]
I was hoping that using this package would magically change functions such as ```toFormattedDateString``` to use the right format not only translations.

Is it simply a problem with the danish translation or is it outside the scope of the project?

Example toFormattedDateString in english would be:

```->format('M d, Y)```

in danish it would be:

```->format('d M,Y)```

**Comment by jenssegers** [comment]
I think that might be a bit too complex to implement.

**Comment by AndreasHeiberg** [comment]
Sure, I guess my 5 cents would be to add a note in the readme
