### ISSUE TITLE
Lumen support

### ISSUE THREAD

**Issue by crisu83** [jenssegers/laravel-date#138]
This package is not compatible with Lumen. The problem is that `DateServiceProvider::boot` calls `$this->app->getLocale()` which does not existing in Lumen. 

I fixed the issue for now by extending the Lumen application and adding a dummy getLocale method that returns the string `'en'`.

I'm rather new to the Laravel ecosystem, so I was hoping that @jenssegers would have a better solution to this issue.

**Comment by eranshmil** [comment]
I replaced that line with:
$locale = $this->app->translator->getLocale();

It's now working in Lumen, but I haven't tested it in Laravel.

**Comment by jenssegers** [comment]
I modified the service provider on dev-master. Let me know if if there are any problems so that I can tag it :)

**Comment by crisu83** [comment]
The change you made on dev-master solves the issue. Thanks for the help.
