### ISSUE TITLE
Subtagged languages are inconsistent with Symfony

### ISSUE THREAD

**Issue by antonioribeiro** [jenssegers/laravel-date#145]
Symphony uses underline (`_`) to subtag a language and laravel-date dash (`-`), as in `pt-BR`, since this is a Laravel package and Symfony is "hard to change", you might want to modify this.

But we also have to consider that [RFC 5646](http://tools.ietf.org/html/rfc5646) tells us to use dash, so now you have to decide if you prefer being right or Symfony consistent... :)

There is an issue in Symfony talking about that but I don't see it changing anytime soon: https://github.com/symfony/symfony/issues/2468

**Comment by jenssegers** [comment]
Changing these would force me to tag a major release though. I don't really know what to do with this.

**Comment by antonioribeiro** [comment]
I'm not sure how are your (pt_BR and zh_TW) users using it, but in Laravel it is probably already broken. 

```
antoniocarlos@titanis [master] 2015-06-29 00:49 /var/www/ak
 $ artisan
Artisan found at ./artisan
PHP Warning:  Uncaught exception 'ErrorException' with message 'require(/var/www/ak/vendor/jenssegers/date/src/Lang/pt_BR.php): failed to open stream: No such file or directory' in /var/www/ak/vendor/jenssegers/date/src/Date.php:370
Stack trace:
#0 /var/www/ak/vendor/jenssegers/date/src/Date.php(370): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'require(/var/ww...', '/var/www/ak/ven...', 370, Array)
#1 /var/www/ak/vendor/jenssegers/date/src/Date.php(370): Jenssegers\Date\Date::setLocale()
#2 /var/www/ak/vendor/jenssegers/date/src/DateServiceProvider.php(23): Jenssegers\Date\Date::setLocale('pt_BR')
#3 [internal function]: Jenssegers\Date\DateServiceProvider->boot()
#4 /var/www/ak/vendor/laravel/framework/src/Illuminate/Container/Container.php(502): call_user_func_array(Array, Array)
#5 /var/www/ak/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(734): Illuminate\Container\Container->call(Array)
#6 /var/www/ak/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(717): Ill in /var/www/ak/vendor/jenssegers/date/src/Date.php on line 370
```

**Comment by jenssegers** [comment]
Unless they set 'pt-BR' in their Laravel config?

**Comment by antonioribeiro** [comment]
Yes, right, but then they will, probably, have a problem in Symfony translation...

**Comment by jenssegers** [comment]
Looks like this repo is using dashes as well: https://github.com/caouecs/Laravel-lang

**Comment by antonioribeiro** [comment]
I'm not saying it's wrong, and the problem with Symfony will occur, basically, when people need to pluralize words, so it's a very specific problem, some users may not have, ever. 

But I have some tests checking for pluralization and that's why I bumped into this. Anyway, feel free to keep it this way until Symfony changes it the correct form: dashes.

**Comment by jenssegers** [comment]
If the Symfony way is the way to go, then I have no issue changing it to underline. Would love to have some more input from pt_BR and zh_TW users though.

**Comment by jenssegers** [comment]
Another solution would be to do some magic before the `setLocale` call and convert underline to dash, which should fix it for both use cases.

**Comment by jenssegers** [comment]
Check out https://github.com/jenssegers/laravel-date/commit/7933306f067f1ce230e31fee91783320627f7326

That should fix this issue.

**Comment by antonioribeiro** [comment]
Nice, I'll test it later. Thank you!
