### ISSUE TITLE
zh-CN.php not found

### ISSUE THREAD

**Issue by wfjsw** [jenssegers/laravel-date#149]
I was installing Cachet when I meet this issue and it probably related to this repo:
```
Jenssegers\Date\Date::setLocale(): Failed opening required '/var/www/html/vendor/jenssegers/date/src/Lang/zh-CN.php' (include_path='.:/usr/share/php:/usr/share/pear') 
```
The app is running on Docker in Debian with Chinese Simplified i18n settings. Any suggestions on that?

**Comment by jenssegers** [comment]
zh-CN does not exists. Only zh-TW. Would be great if you could add it :)

**Comment by wfjsw** [comment]
cp zh.php zh-CN.php

**Comment by phecho** [comment]
:+1: 

this bug also occured in my environment.
