### ISSUE TITLE
Date parse failed

### ISSUE THREAD

**Issue by danieljausovec** [jenssegers/laravel-date#151]
Hi.

I use this date (2015-08-11 19:00:00) and this format (l d F Y H:i) and "sl" language to get human readable date format and i got this error:

DateTime::__construct(): Failed to parse time string (torek 11 avgust 2015 19:00) at position 0 (t): The timezone could not be found in the database

In "en" language works perfect.

**Comment by jenssegers** [comment]
Can you show a code example?

**Comment by danieljausovec** [comment]
Date::setLocale('sl');
return Date::make('2015-08-11 19:00:00')->format('l d F Y H:i');

**Comment by danieljausovec** [comment]
Sorry my mistake. Is my error...
