### ISSUE TITLE
Turkish translation file never reach the plural form.

### ISSUE THREAD

**Issue by Aristona** [jenssegers/laravel-date#49]
Hi,

I've added a PR but would like to inform you about a small bug. When you select the Turkish language, you never reach plural forms.

Will do a PR myself if you guys don't have time.

**Comment by jenssegers** [comment]
Is this fixed in the current version?

**Comment by Aristona** [comment]
@jenssegers I've fixed it with my PR: https://github.com/jenssegers/laravel-date/commit/94819f42ed0cd8785ddb8168ef89d95204caf94d so it is no longer the case.

**Comment by jenssegers** [comment]
Great!
