### ISSUE TITLE
Where should I put new languages files in Laravel ?

### ISSUE THREAD

**Issue by altitude** [jenssegers/laravel-date#53]
Hi !

I'm trying to add a new language file to display 'min' instead of 'minute', etc...

I've created `app/lang/altitude/date.php` and tried to use `Date::setLocale('altitude')` or `App::setLocale('altitude')` but it does not seem to work.

Any idea ?

**Comment by Jellyfrog** [comment]
`app/lang/packages/altitude/date/date.php` in that case

**Comment by altitude** [comment]
Thanks :wink:
