### ISSUE TITLE
Don't detect the laravel locale language and don't show anything when I change the language manually

### ISSUE THREAD

**Issue by jrivera294** [jenssegers/laravel-date#55]
Im trying to set the package language to spanish but It doesn't detect the locale language, the diffForHumans() only show in english. And when I try to set the language manually with " Lang::setLocale('es'); " the  diffForHumans() function return a empty string, without errors, or anything to track the issue.

Pd: The package looks great, I really want to see it working =)

**Comment by halilim** [comment]
@jrivera294, could you be trying to use it like `$etc->created_at->diffForHumans()`? If so, see https://github.com/jenssegers/laravel-date/issues/44.
