### ISSUE TITLE
diffForHumans :count is wrong for locales: ja, zh, zh-TW

### ISSUE THREAD

**Issue by isaacqc** [jenssegers/laravel-date#65]
When I execute: 
<?php 
Date::setLocale('ja');
echo (new Date('2014-10-26'))->diffForHumans(new Date('2014-10-30'));
?>

locale - output:
ja - 1日 前
zh - 1 天 之前
zh-TW - 1 天前
en - 4 days before
fr - 4 jours avant

**Comment by thangngoc89** [comment]
Add vi to the list too https://github.com/jenssegers/laravel-date/pull/96

**Comment by jenssegers** [comment]
Should be fixed in the last tag.
