### ISSUE TITLE
The class dont load the locale config from laravel

### ISSUE THREAD

**Issue by platix** [jenssegers/laravel-date#72]
I was testing it and by default the class doesn't load the locale config from laravel. I can't see the code that load this config from laravel.

I fix it by  putting this code on translator.php
        public function __construct()
    {

        if (class_exists('Illuminate\Support\Facades\Config'))
            $this->locale =\Illuminate\Support\Facades\Config::get('app.locale');

    }

**Comment by jenssegers** [comment]
The translator class is a fallback for the original Laravel translator class.

**Comment by platix** [comment]
I was using this extension with https://github.com/gcphost/laravelcp and it's doesn't load the configured language.
With the fix works pretty well. Thanks for the extension.

**Comment by jenssegers** [comment]
Did you add the service provider?

**Comment by platix** [comment]
I miss it, ':-|
thanks

**Comment by arthurkirkosa** [comment]
I'm having the same problem.

I have the service provider added.

My lang is 'ro'

Where do I have to add the file and what name must it have?

**Comment by jenssegers** [comment]
The best thing would be to create a pull request and add the language file to this project, so that everyone can use it.

**Comment by arthurkirkosa** [comment]
```php
<?php

return array(

    /*
    |--------------------------------------------------------------------------
    | Date Language Lines
    |--------------------------------------------------------------------------
    |
    | The following language lines are used by the date library. Each line can
    | have a singular and plural translation separated by a '|'.
    |
    */

    'ago'       => 'acum :time',
    'from_now'  => ':time de acum',
    'after'     => 'peste :time',
    'before'    => 'acum :time',
    'year'      => 'un an|:count ani',
    'month'     => 'o luna|:count luni',
    'week'      => 'o saptamana|:count saptamani',
    'day'       => 'o zi|:count zile',
    'hour'      => 'o ora|:count ore',
    'minute'    => 'un minut|:count minute|:count minute',
    'second'    => 'o secunda|:count secunde',

    'january'   => 'Ianuarie',
    'february'  => 'Februarie',
    'march'     => 'Martie',
    'april'     => 'Aprilie',
    'may'       => 'Mai',
    'june'      => 'Junie',
    'july'      => 'Julie',
    'august'    => 'August',
    'september' => 'Septembrie',
    'october'   => 'Octobrie',
    'november'  => 'Novembrie',
    'december'  => 'Decembrie',

    'monday'    => 'Luni',
    'tuesday'   => 'Marti',
    'wednesday' => 'Miercuri',
    'thursday'  => 'Joi',
    'friday'    => 'Vineri',
    'saturday'  => 'Sambata',
    'sunday'    => 'Duminica',

);
```

**Comment by arthurkirkosa** [comment]
This is the file

**Comment by jenssegers** [comment]
Do you know how to do a pull request? That way you will be listed as a contributor. If not, I can add it for you.

**Comment by jenssegers** [comment]
Also, according to http://meta.wikimedia.org/wiki/Capitalization_of_Wiktionary_pages#Capitalization_of_month_names, Romanian does not capitalize month and day names.

**Comment by arthurkirkosa** [comment]
Ok, I'll make a pull request with the correct month and day names.

**Comment by jenssegers** [comment]
Tagged in 2.0.11
