### ISSUE TITLE
v2.0.12 not compatible with L4

### ISSUE THREAD

**Issue by ajoah** [jenssegers/laravel-date#75]
Hi,

First of all, thank you for your great library :)

It's just to say that last version (v2.0.12) is no compatible with L4:
![laravel-date-issue](https://cloud.githubusercontent.com/assets/10757301/5973093/8eb07cd8-a864-11e4-8c39-448d5b30bc8b.jpg)

For the moment i had to downgrade my version to v2.0.11

**Comment by jenssegers** [comment]
Damn, I thought I could remove the package registration completely. I'll remove the tag.
