### ISSUE TITLE
Latest Update 2.0.12 gave lang error

### ISSUE THREAD

**Issue by DominikVogt** [jenssegers/laravel-date#76]
Just wanted to inform you, that your latest update caused an error for the language output in laravel 4.

If anyone else is having the same problem, work with 2.0.11 so far.

**Comment by jenssegers** [comment]
Duplicate #75

Tag is already removed.

**Comment by richardfeliciano** [comment]
How can i change to  2.0.11? just put on my composer.json file and update?

**Comment by jenssegers** [comment]
Yes
