### ISSUE TITLE
diffForHumans returning ":date.ago" and ":date.from_now"

### ISSUE THREAD

**Issue by fredrkr** [jenssegers/laravel-date#77]
Using Laravel 4.2 I'm getting the output ":date.ago" and ":date.from_now" from diffForHumans(). Locale doesn't seem to matter, and neither does the preceding method-calls. E.g.:

```php
Date::createFromFormat('Y-m-d', '2015-12-01')->diffForHumans(); // :date.from_now
Date::tomorrow()->diffForHumans(); // :date.from_now
Date::yesterday()->diffForHumans() // :date.ago
```

Tried with both dev-master and 2.0.12, but no cigar.

Am I just being an idiot and missing something very obvious?

**Comment by jenssegers** [comment]
There was an issue with 2.0.12, update master or use 2.0.11 and it should work.

**Comment by richardfeliciano** [comment]
Same issue here, it seems not working for me either. even after downgrade to version 2.0.1.
Date::parse($service->created_at)->diffForHumans(), return ":date.ago".

**Comment by Arrilot** [comment]
You should make another branch and major version for L5 imho

**Comment by jenssegers** [comment]
It should be possible to detect the laravel application version in the service provider and register the language files.
