### ISSUE TITLE
Unable to choose a translation for "un an|:count ani" with locale "ro" for value "45".

### ISSUE THREAD

**Issue by oriceon** [jenssegers/laravel-date#80]
When i use Date::parse(43)->diffForHumans(); i get that error , but in ro lang exists 
'year' => 'un an|:count ani',

as i see, if i put value <= 19 it works... : acum 19 ani

**Comment by jenssegers** [comment]
I'm seeing the same issue. But I don't really know how to fix it, is this something special in the Romanian language?

**Comment by jenssegers** [comment]
Fixed it by doing `un an|:count ani|:count ani`, but I don't know if it is correct.
