### ISSUE TITLE
Can't run composer update : Jenssegers\Date\Date::diffForHumans() should be compatible with Carbon\Carbon::diffForHumans(...)

### ISSUE THREAD

**Issue by rap2hpoutre** [jenssegers/laravel-date#81]
When I run composer update on my project, I have this issue :

exception 'ErrorException' with message 'Declaration of Jenssegers\Date\Date::diffForHumans() should be compatible with Carbon\Carbon::diffForHumans(Carbon\Carbon $other = NULL, $absolute = false)'

I tried on master and last tag. I think it's because any version of carbon is required `"nesbot/Carbon": "*",` in `Jenssegers/Date`'s composer.json, and Carbon was released 4 hours ago.

**Comment by frizbee** [comment]
Same thing, just now

**Comment by jenssegers** [comment]
Merged #73, is the current master working?

**Comment by rap2hpoutre** [comment]
Yes ! It's ok now !

**Comment by frizbee** [comment]
same error for me.

**Comment by leviatan21** [comment]
Hi, this is happening again today, carbon add a new param

Declaration of Jenssegers\Date\Date::diffForHumans() should be compatible with Carbon\Carbon::diffForHumans(Carbon\Carbon $other = NULL, $absolute = false, $short = false, $parts = 1)

**Comment by manu144x** [comment]
@leviatan21 I literally have the same issue exactly right now...

**Comment by DojoGeekRA** [comment]
This is a totally different issue guys, i have opened https://github.com/jenssegers/date/issues/280 to discuss the one related to the `Support for number of interval pieces`

**Comment by ackerchez** [comment]
Same problem here!!!

**Comment by Piusyo** [comment]
Declaration of Jenssegers\Date\Date::diffForHumans() should be compatible with Carbon\Carbon::diffForHumans(Carbon\
Carbon $other = NULL, $absolute = false, $short = false, $parts = 1)

**Comment by danhunsaker** [comment]
Again. This is a different issue resolved three years ago. Please see #280 for the current issue.
