### ISSUE TITLE
Is it possible to extend laravel-date?

### ISSUE THREAD

**Issue by Aristona** [jenssegers/laravel-date#82]
Hi,

I tried extending laravel-date today but failed. (got plently of errors due to laravel-date not being correctly initialized)

Is it possible to extend laravel-date package?

**Comment by jenssegers** [comment]
How would you like to extend it?

**Comment by Aristona** [comment]
I would like to take `Date` facade from this package to myself, and simply extend this class and add my own methods.

Something like:

     class Date extends Jenssegers\Date\Date
     {

           public function diffInWeeksFiltered(callback);

     }

So it should be like this: my date extending your date extending carbon. Is it possible?

**Comment by jenssegers** [comment]
You should be able to just extend the class, no?

**Comment by Aristona** [comment]
Well, your Date package needs to be service provided, where it takes Date alias. (iirc) Not sure how should I write my Date class to extend yours (after yours initializes, probably using defer?) and take Date facade from yours.

**Comment by jenssegers** [comment]
It's only an alias, not an actual facade. You should be able to just change the alias to your class.

**Comment by Aristona** [comment]
Oh, I feel stupid at the moment. I thought I had to run Carbon's service provider, then yours, then mine, and also take Date facade from yours.

All I had to do is: 'Date' => 'My\Date' and do the extension.

This is what happens when you dig deep on IoC while refactoring. :)

Thanks alot for the information. Your package is awesome!
