### ISSUE TITLE
Laravel 5

### ISSUE THREAD

**Issue by Krubb** [jenssegers/laravel-date#87]
Hi! 
I would love an implementation ready for Laravel 5. 

Cause it seems like it doesnt work for Laravel 5 as it is right now at least?

**Comment by jenssegers** [comment]
Laravel 5 support was added since v2.0.13

**Comment by Krubb** [comment]
Thanks for such a quick reply. But it could maybe be good to write out the support of Laravel 5?

And i have some trouble implementing your stuff then. I have done  the installation threw composer, added upp the alias and service provider, changed to 'locale' = 'sv' in config/app.php

And now i want to run the diffForHumans(). But this on a class which i fixed in my model:
protected $dates = ['published_at'];

so i want to print out: $article->published_at->diffForHumans() 

I am fallowing Jeffery Ways tutorial https://laracasts.com/series/laravel-5-fundamentals/episodes/11
He does that in 10:20.

So as you probably understand i am a newbe on laravel. So how do i implement your awesome translations into my project?

**Comment by jenssegers** [comment]
Eloquent converts dates to Carbon instances, you should be able to convert it using:

```
$date = Date::instance($carbon);
```

**Comment by Krubb** [comment]
Soo... (I'm sorry) What does that mean? How should i convert my string? And where?

**Comment by jenssegers** [comment]
Any date in the $dates array of your model class are converted to Carbon objects by the framework. Either you convert those object in your model, by using [accessors](http://laravel.com/docs/4.2/eloquent#accessors-and-mutators) for example, convert them in your controller/view or write specific Presenter classes that wrap your model.

You could do this in your model:

```
public function getPublishedAtAttribute($value)
{
    return Date::instance($value);
}
```

This *should* convert it to a Date instance with milti language support.

**Comment by Krubb** [comment]
Yes and that is what i do in my model when i convert "published_at" to a carbon object:
protected $dates = ['published_at'];

I fallowed Jeffreys example there and i get my carbon object but it is the language part that doesnt seem to work.

**Comment by Krubb** [comment]
I also have https://github.com/caouecs/Laravel4-lang installed and that work just fine
