### ISSUE TITLE
Would it be possible to parse a localized date?

### ISSUE THREAD

**Issue by Evertt** [jenssegers/laravel-date#91]
This will create an error, but it would be nice if it would just work.

    Date::setLocale('nl');
    $d = Date::parse('-1 day')->format('l j F Y H:i:s'); // $d = 'zondag 22 februari 2015 09:37:23'
    Date::createFromFormat('l j F Y H:i:s', $d)->toDateTimeString()

The error is, of course:

    InvalidArgumentException in Carbon.php line 385:
    A textual day could not be found
    A textual month could not be found

Would it be possible to get this to work?

**Comment by jenssegers** [comment]
This feature was added to v3.

**Comment by Evertt** [comment]
Awesome, thank you so much!
